### ISSUE TITLE
Support for  additional types

### ISSUE THREAD

**Issue by amacgregor** [zachdaniel/git_ops#13]
Currently it seems only a few of the commit types from the specification are supported, the full list includes:

- **build**: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
- **ci**: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
- **docs**: Documentation only changes
- **feat**: A new feature
- **fix**: A bug fix
- **perf**: A code change that improves performance
- **refactor**: A code change that neither fixes a bug nor adds a feature
- **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- **test**: Adding missing tests or correcting existing tests

Unless I'm missing something feat, fix, chore are the ones that this library can currently handle.

**Comment by zachdaniel** [comment]
I didn’t add them all to the application by default, but they can be added via the `types` configuration. We probably ought to just support all of them though. Would you be interested in adding that behavior? Should be relatively easy. If not, I can add it this week.

**Comment by zachdaniel** [comment]
Fixed in e7141780fc2f1649518f2641fcf1c52ffd3738ae
