### ISSUE TITLE
Running mix git_ops.release --initial --dry-run creates Changelog.md

### ISSUE THREAD

**Issue by djantea** [zachdaniel/git_ops#18]
If git_ops was just added to your project and you want to run `git_ops.release --initial` in dry run mode, i.e. `git_ops.release --initial --dry-run --dry-run`, the Changelog.md file is still created. So if you want to run `git_ops.release --initial` after that, it will fail because Changelog.md already exists, and the tool will ask you to delete it first before re-trying.

In my mind, running the mix task in dry run mode, shouldn't change anything on the disk, so that it will not affect subsequent executions of the same task.

**Comment by zachdaniel** [comment]
Yes, I completely agree. Would you be interested in contributing a fix for it? If not, I will get to it when I can :)

**Comment by zachdaniel** [comment]
#19 was merged and released as version 0.6.4 on hex.
