### ISSUE TITLE
Is it possible for git_ops to work with elixir app in a subdirectory? 

### ISSUE THREAD

**Issue by benwoodward** [zachdaniel/git_ops#37]
I have a Phoenix API app in `project-name/backend` and JS web client in `project-name/client`. Is it possible for git_ops to work with the Phoenix app in a subdirectory? 

I tried modifying `project-name/.git/hooks/commit-msg` command to `MIX_EXS=backend/mix.exs mix git_ops.check_message "$@"` but I get errors: 

```
Unchecked dependencies for environment dev:
* ex_aws_s3 (Hex package)
  the dependency is not available, run "mix deps.get"
* another_dep (Hex package)
  the dependency is not available, run "mix deps.get"
* another_dep (Hex package)
  the dependency is not available, run "mix deps.get"
* another_dep (Hex package)
  the dependency is not available, run "mix deps.get"
```

**Comment by zachdaniel** [comment]
What if you tried something like `cd backend && mix git_ops.check_message`?
