### ISSUE TITLE
Append the current release's changelog body to the git tag message

### ISSUE THREAD

**Issue by frankdugan3** [zachdaniel/git_ops#43]
This will have several benefits, particularly that with GitHub releases, the tag's message will be added into the body.

As @zachdaniel mentioned in a Discord conversation, the implementation should be pretty easy to add:

> We'll probably need to update the `Changelog.write!/5` function to return the text contents that it wrote to the changelog, and then pass that into the `confirm_and_tag` function

**Comment by zachdaniel** [comment]
I won't have much time to focus on this, but I'll try to get around to it in the next couple weeks. If anyone else wants to tackle it I'd be grateful.

**Comment by frankdugan3** [comment]
I may take a stab at this. Do you think it would be better for `Changelog.write/5` to return just the `new_content`, or perhaps a map/tuple containing both the entire changelog and `new_content`?

**Comment by zachdaniel** [comment]
Probably just the `new_content` since the whole file itself isn't needed for anything further down the line.

**Comment by zachdaniel** [comment]
This was completed.
