### ISSUE TITLE
License Change GPL -> MIT

### ISSUE THREAD

**Issue by zachdaniel** [zachdaniel/git_ops#45]
Hey everyone! I'm reaching out because you're a contributor on my `git_ops` project on GitHub. The project can be found here: https://github.com/zachdaniel/git_ops. I've been notified that the license is actually much less permissive than we'd expect. Specifically, it is very *unpermissive*. Technically this means its a legal issue for those using it in their closed source work projects. However, this license is *not* in the spirit of what the creators intended. For ethical reasons, it is my responsibility to reach out to each contributor and confirm that they are okay with their work being relicensed under the MIT software license, which is extremely permissive. If those users would then like to update to the latest version of git_ops with that new license (once it is published) then all is well with the world and no one needs to worry.

Some names may already be checked off, which means that I received confirmation from them through various media. If I was able to contact them by email, their email is *not* included here for their own privacy.

- [x] @zachdaniel 
- [x] @tomplarge (linkedin)
- [x] @asummers (over discord private message)
- [x] @jimsynz 
- [x] @kianmeng 
- [x] @djantea (responded in this thread)
- [x] @sneako (reached out over twitter)
- [x] @marinakr (reached out over email)
- [x] @frankdugan3 (spoken in the Ash Elixir discord channel)
- [x] @benwoodward (responded in this thread)

If we can't get ahold of @benwoodward we can undo his changes until we hear from him (or permanently if we never do):
https://github.com/zachdaniel/git_ops/commit/97db3b5fa65405485c62bc936416d07b90f84dcd

**Comment by zachdaniel** [comment]
![CleanShot 2021-01-08 at 13 50 05](https://user-images.githubusercontent.com/5722339/104052927-6ed1af00-51b8-11eb-9f22-bd9e32afc1e2.png)

**Comment by zachdaniel** [comment]
![CleanShot 2021-01-08 at 13 51 56](https://user-images.githubusercontent.com/5722339/104053124-b6583b00-51b8-11eb-983e-a42869b81c96.png)

**Comment by zachdaniel** [comment]
![CleanShot 2021-01-08 at 13 56 06](https://user-images.githubusercontent.com/5722339/104053478-4e562480-51b9-11eb-9bc9-db0568c68bba.png)

**Comment by frankdugan3** [comment]
I approve of changing to any open-source license, including MIT or LGPL, and further relinquish copyright of my contributed code to @zachdaniel.

**Comment by djantea** [comment]
Hi Daniel,

I agree with changing the licence of the project to MIT licence.

Best regards,
Dan

**Comment by benwoodward** [comment]
Sorry, on holiday. Just saw this. You have my permission to use my code under the MIT license. 

EDIT: Had to check to see what code I contributed. Changing a single line in the README haha

**Comment by zachdaniel** [comment]
Awesome! Thanks @benwoodward. Apologies for interrupting your vacation.

**Comment by kianmeng** [comment]
@zachdaniel Permission granted to switch from GPL to MIT.

**Comment by zachdaniel** [comment]
Thanks so much!

**Comment by asummers** [comment]
(To normalize it all into one place) Permission granted to switch license from GPL to MIT.

**Comment by jimsynz** [comment]
@zachdaniel I am happy to relicense my contributions as MIT. Go forth and share.

**Comment by zachdaniel** [comment]
Thank you everyone for timely responses and making this happen. Hope you all have a great 2020!

**Comment by jimsynz** [comment]
> Thank you everyone for timely responses and making this happen. Hope you all have a great 2020!

Classic off by one error.

**Comment by zachdaniel** [comment]
Lol, just shows how much I wish this last year wasn't real.
