### ISSUE TITLE
Custom Path for .git folder

### ISSUE THREAD

**Issue by tensor-programming** [zachdaniel/git_ops#52]
Went through the code and didn't see anything like this.  My project is a "poncho" setup in that its a bunch of apps in a parent directory (they don't share a mix file).  I want to be able to use Git Ops to generate a changelog by installing it on one of the apps (the main entry point) and using the custom commits to delineate between the different libraries but it won't let me define where the `.git` folder is and instead just initializes a `.git` folder in the app's folder.  Is there some way to do this that I am missing?

**Comment by zachdaniel** [comment]
Unfortunately there is nothing for that currently. But a PR is welcome! It may hopefully be as simple as adding a command line flag for the directory the `.git` is in, and then add it to the args automatically when using everything in this file: https://github.com/zachdaniel/git_ops/blob/master/lib/git_ops/git.ex. That way there would be no need to go change lots of things in the calling code.

**Comment by tensor-programming** [comment]
Alright thanks mate.  I might just do that.
