### ISSUE TITLE
Hexdocs page is broken

### ISSUE THREAD

**Issue by Gladear** [zachdaniel/git_ops#67]
On [hexdocs.pm](https://hexdocs.pm/git_ops/readme.html), the navigation menu does not load correctly.

![](https://github.com/user-attachments/assets/97fd0c77-a3d4-4aab-b76c-2398d4c19997)

I tried on Chromium and Firefox, both without any extension. I tried to clone and build the documentation locally, and the problem does not seem to appear there. I did not investigate any further, sorry for that.

**Comment by zachdaniel** [comment]
Thank you for letting me know. 🙇  This was a strange issue. I had to update the package and push a new docs version to fix it for some reason 🤷

**Comment by Gladear** [comment]
Thank you for the fast fix 😄
