### ISSUE TITLE
Allow version_tag_prefix empty string

### ISSUE THREAD

**Issue by marinakr** [zachdaniel/git_ops#9]
https://github.com/zachdaniel/git_ops/blob/master/lib/mix/tasks/git_ops.release.ex#L103
prefix "" is not allowed by code `String.trim_leading(prefixed_new_version, prefix)` - second arg could not be empty

**Comment by zachdaniel** [comment]
This has been resolved, thanks to @marinakr with #11 and released in version `0.6.0`
